### ISSUE TITLE
Unreadable object

### ISSUE THREAD

**Issue by Cclleemm** [karstenBriksoft/PlistExplorer#8]
Hello,

thank you for this tool, it works very well.
Howover, I have a problem with a type of object, I have "nil" value but in my PLIST I have something like that.

<img width="382" alt="capture d ecran 2017-02-07 a 08 11 29" src="https://cloud.githubusercontent.com/assets/1133341/22682486/23d5cf1c-ed13-11e6-88ea-dd4224c6c10d.png">

Do you have an idea of what kine of object (or primitive) it can be ? 
How can I do to decode that ?

Thank you very much

**Comment by karstenBriksoft** [comment]
according to: http://svn.gna.org/svn/gnustep/libs/base/trunk/Source/NSCoder.m it seems to be a _NSKeyedCoderOldStyleArray. The type according to https://opensource.apple.com/source/objc4/objc4-274/runtime/objc-class.h.auto.html the 67 means 'C', means _C_UCHR, which is according to https://opensource.apple.com/source/gcc/gcc-5484/libobjc/encoding.c.auto.html an unsigned char.
So basically this means it's just the bytes 30, 59 and -128, -128.

**Comment by karstenBriksoft** [comment]
The PListExplorer doesn't know about the unsigned value. 
I don't know how you can decode the date. I've never used Swift.

**Comment by Cclleemm** [comment]
If you have an idea to decode that in Objective-C it can help me :)

**Comment by karstenBriksoft** [comment]
not out of my head but from the web-sites that i've linked earlier it appears that NSArchiver may already be capable of decoding these objects.

**Comment by Cclleemm** [comment]
Ok, I will make some research, I will notice you when I'll find the solution.

Thank you for clues

**Comment by Cclleemm** [comment]
Thank you, il was an array of unsigned char (2). I decoded it with the method decodeArrayOfObjCType.

`unsigned char *arrayOfUChars = (unsigned char *)calloc(2, sizeof(unsigned char));
    [aDecoder decodeArrayOfObjCType:@encode(unsigned char) count:2 at: arrayOfUChars];
    int r1 = (int) arrayOfUChars[0];
    int r2 = (int) arrayOfUChars[1];`

Thank you very much, without your help I would never have found
